### ISSUE TITLE
why is the processor so heavily loaded?

### ISSUE THREAD

**Issue by xxlilx** [WzrterFX/imgui-directx-overlay#1]

**Comment by WzrterFX** [comment]
Change:
```g_d3dpp.PresentationInterval = D3DPRESENT_INTERVAL_IMMEDIATE;``` // unbound fps
To:
```g_d3dpp.PresentationInterval = D3DPRESENT_INTERVAL_ONE;``` // vsync

I deliberately made the maximum priority = ) 
I'll probably update the repository
